### ISSUE TITLE
MarkupText only renders first child when using fallback

### ISSUE THREAD

**Issue by nephix** [synacor/preact-i18n#20] opened 2018-05-13 05:46 UTC
# Steps:

1. Go to https://codesandbox.io/s/1zzm1n6npq
2. Open `en.json` and locate `news.title` property
3. See the correct output in result window: `<span>This <em>should work</em></span>`
4. Change `news.title` in `index.js` to `news.whatever`

# Expected Result:
The default text
`<span>This <b>This doesnt work</b></span>`
is rendered in the result window

# Actual Result:
`<span>This </span>`
is rendered in the result window

**Comment by azizhk** [comment] 2018-05-14 04:55
This is because the following code seems to pick only the first child.
https://github.com/synacor/preact-i18n/blob/0287d0f1a5eabc050a475cee160ecedd7463145b/src/components/text.js#L44

**Comment by billneff79** [comment] 2018-05-15 01:55
That _is_ likely the issue.  I would be happy to review a PR that changes it to just `fallback = children` and added test cases for a fallback with markup in it.

**Comment by nephix** [comment] 2018-05-17 14:30
Hey @azizhk, thank you. Although that fixes the problem, it lets a bunch of other test cases fail.

**Comment by nephix** [comment] 2018-05-18 17:20
Is there a chance of this getting fixed and released any time soon? It's currently blocking us from rolling out our app in another location.

**Comment by pl12133** [comment] 2018-05-18 17:30
@nephix Surely, I would be happy to review a PR with the fix recommended by @azizhk.

**Comment by nephix** [comment] 2018-05-18 17:32
@pl12133 sure, but the fix brings a whole lot of other issues when you run the tests that I'm not able to fix.

**Comment by azizhk** [comment] 2018-05-18 19:02
Created a PR https://github.com/synacor/preact-i18n/pull/21

**Comment by billneff79** [comment] 2018-05-18 21:32
This is resolved in `preact-i18n@1.2.1`

**Closed by billneff79** 2018-05-18 21:32 UTC

**Comment by gavmck** [comment] 2020-02-12 13:45
Same issue with the basic `<Text>` field caused by the same line of code by the looks of it
